/**
 * aws-exports.js
 *
 * This file is auto-generated by `amplify push` from the backend folder.
 * After running `amplify push` in /backend, copy the generated aws-exports.js here,
 * or run `amplify pull` inside the frontend folder pointing to your Amplify app.
 *
 * Template values below — replace with real values after deploying backend.
 */

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id: "us-east-1:REPLACE_WITH_IDENTITY_POOL_ID",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_REPLACE",
  aws_user_pools_web_client_id: "REPLACE_WITH_CLIENT_ID",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint: "https://REPLACE.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "REPLACE_WITH_API_KEY",
  aws_user_files_s3_bucket: "gmailclone-storage-REPLACE",
  aws_user_files_s3_bucket_region: "us-east-1",
};

export default awsmobile;
